apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp10
  namespace: mytg1
spec:
  replicas: 4
  selector:
    matchLabels:
      env: surender
      prod: nginx
  template:
    metadata:
      labels:
        env: surender
        prod: nginx
    spec:
      imagePullSecrets:
        - name: mypasswd-for-custom-img
      containers:
        - name: c1
          image: surendersinghbisht/surender2024:BUILD_NUMBER
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "128m"

