apiVersion: v1
kind: Service
metadata:
  name: service-po88
  namespace: mytg1
spec:
  type: NodePort
  selector:
    env: surender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32381
